base_url = "https://maguro.dev"
compile_sass = true
highlight_code = true
build_search_index = true
default_language = "en"
theme = "even"
title = "maguro.dev"
description = "Blog by maguro_tuna"
highlight_theme = "one-dark"
taxonomies = [
    { name = "tags", rss = true },
]

[extra]
even_title = "maguro.dev"
even_menu = [
  { url = "$BASE_URL", name = "Home" },
  { url = "$BASE_URL/about", name = "About" },
  { url = "$BASE_URL/apps", name = "Apps" },
]
katex_enable = true
katex_auto_render = true
