base_url = "https://maguro.dev"
compile_sass = true
highlight_code = true
build_search_index = true
default_language = "en"
theme = "even"
title = "maguro.dev"
description = "Blog by maguro_tuna"
highlight_theme = "gruvbox-dark"

[extra]
even_title = "maguro.dev"
author = "maguro_tuna"
show_author = true
show_categories = true
show_tags = true
theme_color = "orange"
show_menu_items = 2
full_width = false
logo_text = "zerm"
logo_home_link = "/"
main_menu = [
  { url = "/about", name = "about" },
  { url = "/contact", name = "contact" },
]
menu_more = "show more"
read_more = "read more"
read_other_posts = "read other posts"
texonomies = [
  { name = "categories", rss = true },
  { name = "tags", rss = true },
]
